/**
 * Cabineato Type Definitions
 *
 * Re-exports all types and constants for easy importing.
 */

// Types
export type {
  Vector2,
  Vector3,
  HoleFeature,
  SlotFeature,
  NotchFeature,
  CountersinkFeature,
  Feature,
  CNCLayer,
  ComponentRole,
  Component,
  MaterialConfig,
  SecondaryMaterialConfig,
  MachiningConfig,
  BackPanelType,
  BackPanelConfig,
  AdjustableShelfConfig,
  FixedShelfConfig,
  DrawerRunnerMode,
  ShelfRunnerConfig,
  ShelfConfig,
  DrawerPullType,
  DrawerPullConfig,
  DrawerConfig,
  ToeKickConfig,
  CarcassJointType,
  CarcassJointConfig,
  BackStretcherConfig,
  AssemblyPredrillConfig,
  SlidePredrillConfig,
  GlobalBounds,
  AssemblyConfig,
  Assembly,
  ComponentOutline,
  LayeredExport,
} from './assembly';

// Constants
export {
  SYSTEM_32,
  CNC_LAYERS,
  MATERIAL_THICKNESSES,
  BIT_DIAMETERS,
  DRAWER_DEFAULTS,
  DRAWER_PULL_DEFAULTS,
  TOE_KICK_DEFAULTS,
  TOLERANCES,
  BACK_PANEL_DEFAULTS,
  DADO_DEFAULTS,
  ASSEMBLY_PREDRILL_DEFAULTS,
  SLIDE_HARDWARE_DEFAULTS,
  SHELF_RUNNER_DEFAULTS,
  DEFAULT_MATERIAL,
  DEFAULT_SECONDARY_MATERIAL,
  DEFAULT_MACHINING,
  DEFAULT_BACK_PANEL,
  DEFAULT_ADJUSTABLE_SHELVES,
  DEFAULT_FIXED_SHELVES,
  DEFAULT_SHELF_RUNNERS,
  DEFAULT_SHELVES,
  DEFAULT_DRAWER_PULLS,
  DEFAULT_DRAWERS,
  DEFAULT_TOE_KICK,
  DEFAULT_CARCASS_JOINT,
  DEFAULT_BACK_STRETCHERS,
  BACK_STRETCHER_DEFAULTS,
  POCKET_HOLE_DEFAULTS,
  DEFAULT_ASSEMBLY_PREDRILLS,
  DEFAULT_SLIDE_PREDRILLS,
  DEFAULT_ASSEMBLY_CONFIG,
  BED_SIZES,
  NESTING_DEFAULTS,
  DEFAULT_NESTING_CONFIG,
  MM_PER_INCH,
  mmToInches,
  inchesToMm,
  formatAsInches,
} from './constants';
